// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEbRIB7WEQRE84HxH0CH_V8WOoHUnIPd8',
    appId: '1:278929890705:web:9066d1a6a34159ac3ece30',
    messagingSenderId: '278929890705',
    projectId: 'ridesharefyp-0022',
    authDomain: 'ridesharefyp-0022.firebaseapp.com',
    storageBucket: 'ridesharefyp-0022.firebasestorage.app',
    measurementId: 'G-32WJN8QL8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrj_kBnHFI8BZ7-DlTSnBbW-lli50NTg',
    appId: '1:278929890705:android:049186d5a0c4183d3ece30',
    messagingSenderId: '278929890705',
    projectId: 'ridesharefyp-0022',
    storageBucket: 'ridesharefyp-0022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBay9sYuFkcApCsw4mYh6n_fT_edNObg',
    appId: '1:278929890705:ios:95133131e216c75e3ece30',
    messagingSenderId: '278929890705',
    projectId: 'ridesharefyp-0022',
    storageBucket: 'ridesharefyp-0022.firebasestorage.app',
    iosBundleId: 'com.example.femdrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBay9sYuFkcApCsw4mYh6n_fT_edNObg',
    appId: '1:278929890705:ios:95133131e216c75e3ece30',
    messagingSenderId: '278929890705',
    projectId: 'ridesharefyp-0022',
    storageBucket: 'ridesharefyp-0022.firebasestorage.app',
    iosBundleId: 'com.example.femdrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEbRIB7WEQRE84HxH0CH_V8WOoHUnIPd8',
    appId: '1:278929890705:web:8048119b84e43da03ece30',
    messagingSenderId: '278929890705',
    projectId: 'ridesharefyp-0022',
    authDomain: 'ridesharefyp-0022.firebaseapp.com',
    storageBucket: 'ridesharefyp-0022.firebasestorage.app',
    measurementId: 'G-46QGL761PR',
  );
}
